name: CD - Deploy to EKS via Terraform

on:
  repository_dispatch:
    types: [ image-pushed ]

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init/Apply
        run: |
          cd terraform
          terraform init -input=false
          terraform workspace select prod || terraform workspace new prod
          terraform apply -auto-approve -var "image=${{ github.event.client_payload.image }}"
